datasources:
  default:
    url: jdbc:mysql://localhost:4000/simonsthings
    username: root
    password: ''
    dialect: mysql
    driver-class-name: com.mysql.cj.jdbc.Driver

flyway:
  datasources:
    default:
      url: jdbc:mysql://localhost:4000/simonsthings
      user: root
      password: ""

