version: '3.1'

services:
  db:
    image: mysql:8.0.21
    container_name: simons-things-mysql
    environment:
      MYSQL_ROOT_PASSWORD: ''
      MYSQL_ALLOW_EMPTY_PASSWORD: 'true'
      MYSQL_USER: simonsthings
      MYSQL_PASSWORD: ''
    command: --character-set-server=utf8 --collation-server=utf8_unicode_ci --init-connect='SET collation_connection = utf8_unicode_ci;'
    ports:
    - 4000:3306

